### ISSUE TITLE
Release for security updates

### ISSUE THREAD

**Issue by shizhMSFT** [oras-project/artifacts-spec#79]
Proposing we release `v1.0.0-draft.2` for doc and security updates.

**Comment by SteveLasker** [comment]
[Draft 2](https://github.com/oras-project/artifacts-spec/milestone/3) still has at least two items tracked before cutting the draft. 

The big one is the content breaking change for [`[blobs]` to `[descriptors]`](https://github.com/oras-project/artifacts-spec/issues/73), which we're just making a name change now, for possible future usage. 
#74 is blocked on distribution merging the pr. Since it's not a persisted data change, while unfortunate, I wouldn't say it's blocking at this point.

**Comment by shizhMSFT** [comment]
Thanks @SteveLasker for the details behind the `draft.2`. Since we haven't reached the milestone [1.0.0.draft.2](https://github.com/oras-project/artifacts-spec/milestone/3), we cannot release with the security updates as `v1.0.0-draft.2`.

The tag name `v1.0.1-draft.1` is not an option as we are targeting `v1.0.0`. Then releasing with the same tag name `v1.0.0-draft.1` is our only option.

**Comment by shizhMSFT** [comment]
@SteveLasker proposed `draft.1.1`. I've tested that
```
v1.0.0-draft.1 < v1.0.0-draft.1.1 < v1.0.0-draft.2
```
Yes, `v1.0.0-draft.1.1` is a better option.

**Comment by SteveLasker** [comment]
for lack of a better option 👍 for v1.0.0-draft.1.1

**Comment by sajayantony** [comment]
LGTM. `v1.0.0-draft.1.1` You can update the issue and share the digest you want to tag?

**Comment by shizhMSFT** [comment]
@sajayantony I am tagging ac46408936e8c03d53ece23b2b7b0616e0858491 as `v1.0.0-draft.1.1`.

**Comment by shizhMSFT** [comment]
Released [v1.0.0-draft.1.1](https://github.com/oras-project/artifacts-spec/releases/tag/v1.0.0-draft.1.1).

**Comment by corburn** [comment]
Links in the [v1.0.0-draft.1.1](https://github.com/oras-project/artifacts-spec/releases/tag/v1.0.0-draft.1.1) release notes point to the prior v1.0.0-draft.1 documentation.
